apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
      - name: products-api
        image: rafaltaraska/products-api:latest
        env:
          - name: MYSQL_HOST
            value: "store-database"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DATABASE
            value: "storedb"
          - name: MYSQL_USERNAME
            value: "user"
          - name: MYSQL_PASSWORD
            value: "rootpassword"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_QUEUE_NAME
            value: "orders_queue"
        ports:
          - containerPort: 8080
