version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: store-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: user
      MYSQL_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: message-queue
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  products-api:
    build:
      context: ./products-api
    environment:
      MYSQL_HOST: store-database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: mysqldb
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: rootpassword
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"

  notifications-api:
    build:
      context: ./notifications-api
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE_NAME: orders_queue
    depends_on:
      - rabbitmq
    ports:
      - "5001:5001"

  store-frontend:
    build:
      context: ./store-frontend
    depends_on:
      - products-api
    ports:
      - "3000:3000"

volumes:
  mysql_data:
